require('dotenv').config();
const mongoose =  require('mongoose');
const _ = require('lodash');
const { ClassModel } = require('../models/classes');
const moment = require('moment');

const mongoURI = `mongodb+srv://${process.env.DB_USER}:${process.env.DB_PASS}@${process.env.DB_HOST}/${process.env.DB_NAME}`

//data 
let data = [
    {"orgName":"Johnath Gullivan","email":"jgullivan0@nationalgeographic.com","contact":"5444305664","nameOfClass":"HIIT with Me","genreOfExercise":"HIIT","noOfSessions":1,"capacity":10,"price":50,"startDateTime":"2021-07-20T08:47:24","endDateTime":"2021-07-20T09:47:24","mode":"Physical","location":"Bayside","minAge":"16","maxAge":null,"gender":"Female","details":"eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient","typeOfExercise":"Flexibility","image":"http://dummyimage.com/50x50.png/ff4444/ffffff"},
    {"orgName":"Hamilton Johanchon","email":"hjohanchon1@purevolume.com","contact":"9264085126","nameOfClass":"Yoga in the Park","genreOfExercise":"Yoga","noOfSessions":1,"capacity":30,"price":30,"startDateTime":"2021-08-11T23:45:11","endDateTime":"2021-08-12T00:45:11","mode":"Online","location":"International","minAge":"21","maxAge":null,"gender":"All","details":"odio elementum eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin","typeOfExercise":"Flexibility","image":"http://dummyimage.com/50x50.png/5fa2dd/ffffff"},
    {"orgName":"Finlay Fairclough","email":"ffairclough2@w3.org","contact":"8955893647","nameOfClass":"Swimming for kids","genreOfExercise":"Swimming","noOfSessions":12,"capacity":30,"price":20,"startDateTime":"2021-06-22T01:39:56","endDateTime":"2021-06-22T02:39:56","mode":"Physical","location":"Warrior","minAge":"16","maxAge":null,"gender":"All","details":"ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede","typeOfExercise":"Flexibility","image":"http://dummyimage.com/50x50.png/5fa2dd/ffffff"},
    {"orgName":"Jocko Greest","email":"jgreest3@networksolutions.com","contact":"7658075881","nameOfClass":"Swimming for adults","genreOfExercise":"Swimming","noOfSessions":15,"capacity":10,"price":25,"startDateTime":"2021-12-16T04:02:09","endDateTime":"2021-12-16T05:02:09","mode":"Online","location":"Oak","minAge":"null","maxAge":null,"gender":"Female","details":"viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac consequat metus","typeOfExercise":"Flexibility","image":"http://dummyimage.com/50x50.png/cc0000/ffffff"},
    {"orgName":"Karna Trunby","email":"ktrunby4@yandex.ru","contact":"2904905972","nameOfClass":"Basketball for all","genreOfExercise":"Basketball","noOfSessions":10,"capacity":10,"price":40,"startDateTime":"2021-07-31T05:09:13","endDateTime":"2021-07-31T06:09:13","mode":"Online","location":"Welch","minAge":"7","maxAge":null,"gender":"Female","details":"phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor turpis","typeOfExercise":"Endurance","image":"http://dummyimage.com/50x50.png/ff4444/ffffff"},
    {"orgName":"Kylen Tenbrug","email":"ktenbrug5@1688.com","contact":"3724993413","nameOfClass":"Tennis for mommies","genreOfExercise":"Tennis","noOfSessions":1,"capacity":20,"price":20,"startDateTime":"2021-10-03T18:20:23","endDateTime":"2021-10-03T19:20:23","mode":"Physical","location":"Drewry","minAge":"12","maxAge":null,"gender":"Male","details":"nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum","typeOfExercise":"Flexibility","image":"http://dummyimage.com/50x50.png/dddddd/000000"},
    {"orgName":"Lauritz Mayberry","email":"lmayberry6@guardian.co.uk","contact":"2908207505","nameOfClass":"KpopXFitness finesse","genreOfExercise":"KpopXFitness","noOfSessions":1,"capacity":20,"price":30,"startDateTime":"2021-10-15T20:39:18","endDateTime":"2021-10-15T21:39:18","mode":"Physical","location":"Hayes","minAge":"null","maxAge":null,"gender":"All","details":"nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor","typeOfExercise":"Flexibility","image":"http://dummyimage.com/50x50.png/5fa2dd/ffffff"},
    {"orgName":"Delcine Goldsack","email":"dgoldsack7@yellowbook.com","contact":"2359608955","nameOfClass":"Bollywood for good","genreOfExercise":"Bollywood","noOfSessions":15,"capacity":20,"price":50,"startDateTime":"2021-08-14T15:58:39","endDateTime":"2021-08-14T16:58:39","mode":"Physical","location":"Continental","minAge":"18","maxAge":null,"gender":"All","details":"ipsum dolor sit amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis","typeOfExercise":"Flexibility","image":"http://dummyimage.com/50x50.png/dddddd/000000"},
    {"orgName":"Leigha Blabie","email":"lblabie8@arstechnica.com","contact":"8691106242","nameOfClass":"Bobsledding only for Bobs","genreOfExercise":"Bobsled","noOfSessions":10,"capacity":20,"price":45,"startDateTime":"2021-12-27T01:06:41","endDateTime":"2021-12-27T02:06:41","mode":"Physical","location":"Kipling","minAge":"7","maxAge":null,"gender":"All","details":"arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna","typeOfExercise":"Endurance","image":"http://dummyimage.com/50x50.png/ff4444/ffffff"},
    {"orgName":"Vivi Insko","email":"vinsko9@ehow.com","contact":"8979430229","nameOfClass":"Kickbox for Hogs","genreOfExercise":"Kickbox","noOfSessions":15,"capacity":30,"price":20,"startDateTime":"2021-07-08T01:00:23","endDateTime":"2021-07-08T02:00:23","mode":"Physical","location":"Linden","minAge":"null","maxAge":null,"gender":"Male","details":"gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat","typeOfExercise":"Endurance","image":"http://dummyimage.com/50x50.png/dddddd/000000"},
    {"orgName":"Nady Langlois","email":"nlangloisa@gov.uk","contact":"5892820852","nameOfClass":"Water Polo with Marco","genreOfExercise":"Water Polo","noOfSessions":15,"capacity":20,"price":25,"startDateTime":"2021-10-24T23:49:24","endDateTime":"2021-10-25T00:49:24","mode":"Physical","location":"Karstens","minAge":"21","maxAge":null,"gender":"Female","details":"posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede","typeOfExercise":"Flexibility","image":"http://dummyimage.com/50x50.png/cc0000/ffffff"},
    {"orgName":"Miles Tripett","email":"mtripettb@nhs.uk","contact":"1544734198","nameOfClass":"Abs Buns Thighs","genreOfExercise":"ABT","noOfSessions":10,"capacity":10,"price":35,"startDateTime":"2021-12-25T12:31:41","endDateTime":"2021-12-25T13:31:41","mode":"Physical","location":"Vermont","minAge":"null","maxAge":null,"gender":"Female","details":"ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit","typeOfExercise":"Balance","image":"http://dummyimage.com/50x50.png/5fa2dd/ffffff"},
    {"orgName":"Benetta Goncaves","email":"bgoncavesc@zdnet.com","contact":"3636684626","nameOfClass":"Discus and Biscuits","genreOfExercise":"Discus","noOfSessions":15,"capacity":10,"price":20,"startDateTime":"2021-07-09T15:19:19","endDateTime":"2021-07-09T16:19:19","mode":"Physical","location":"Reinke","minAge":"12","maxAge":null,"gender":"All","details":"vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh","typeOfExercise":"Endurance","image":"http://dummyimage.com/50x50.png/cc0000/ffffff"},
    {"orgName":"Grant Corlett","email":"gcorlettd@topsy.com","contact":"4596245679","nameOfClass":"HIIT with Me","genreOfExercise":"HIIT","noOfSessions":10,"capacity":20,"price":25,"startDateTime":"2021-07-08T04:26:27","endDateTime":"2021-07-08T05:26:27","mode":"Physical","location":"Jackson","minAge":"18","maxAge":null,"gender":"Male","details":"vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel","typeOfExercise":"Strength","image":"http://dummyimage.com/50x50.png/5fa2dd/ffffff"},
    {"orgName":"Glynis Torbard","email":"gtorbarde@php.net","contact":"2013110276","nameOfClass":"Yoga in the Park","genreOfExercise":"Yoga","noOfSessions":15,"capacity":10,"price":50,"startDateTime":"2021-09-26T07:24:08","endDateTime":"2021-09-26T08:24:08","mode":"Online","location":"Eagan","minAge":"null","maxAge":null,"gender":"All","details":"quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor","typeOfExercise":"Endurance","image":"http://dummyimage.com/50x50.png/dddddd/000000"},
    {"orgName":"Felicle Dargan","email":"fdarganf@si.edu","contact":"3871083213","nameOfClass":"Swimming for kids","genreOfExercise":"Swimming","noOfSessions":10,"capacity":10,"price":35,"startDateTime":"2021-11-21T15:37:01","endDateTime":"2021-11-21T16:37:01","mode":"Online","location":"Barnett","minAge":"21","maxAge":null,"gender":"Male","details":"libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient","typeOfExercise":"Endurance","image":"http://dummyimage.com/50x50.png/dddddd/000000"},
    {"orgName":"Allyce Gannicleff","email":"agannicleffg@archive.org","contact":"7706459278","nameOfClass":"Swimming for adults","genreOfExercise":"Swimming","noOfSessions":10,"capacity":10,"price":0,"startDateTime":"2021-06-28T04:59:35","endDateTime":"2021-06-28T05:59:35","mode":"Physical","location":"Burrows","minAge":"16","maxAge":null,"gender":"Male","details":"fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu","typeOfExercise":"Endurance","image":"http://dummyimage.com/50x50.png/cc0000/ffffff"},
    {"orgName":"Bale Goldstone","email":"bgoldstoneh@reverbnation.com","contact":"7137958340","nameOfClass":"Basketball for all","genreOfExercise":"Basketball","noOfSessions":10,"capacity":20,"price":25,"startDateTime":"2021-11-21T13:06:55","endDateTime":"2021-11-21T14:06:55","mode":"Online","location":"Dwight","minAge":"7","maxAge":null,"gender":"All","details":"varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat","typeOfExercise":"Strength","image":"http://dummyimage.com/50x50.png/dddddd/000000"},
    {"orgName":"Marlowe Routham","email":"mrouthami@sphinn.com","contact":"7729445189","nameOfClass":"Tennis for mommies","genreOfExercise":"Tennis","noOfSessions":12,"capacity":20,"price":25,"startDateTime":"2021-10-10T17:18:41","endDateTime":"2021-10-10T18:18:41","mode":"Online","location":"Redwing","minAge":"16","maxAge":null,"gender":"All","details":"sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum","typeOfExercise":"Balance","image":"http://dummyimage.com/50x50.png/cc0000/ffffff"},
    {"orgName":"Cristal Kindread","email":"ckindreadj@cpanel.net","contact":"4431364698","nameOfClass":"KpopXFitness finesse","genreOfExercise":"KpopXFitness","noOfSessions":15,"capacity":10,"price":15,"startDateTime":"2021-12-01T15:53:54","endDateTime":"2021-12-01T16:53:54","mode":"Online","location":"Carberry","minAge":"21","maxAge":null,"gender":"Male","details":"laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede","typeOfExercise":"Balance","image":"http://dummyimage.com/50x50.png/ff4444/ffffff"},
    {"orgName":"Bertrando Eate","email":"beatek@businessweek.com","contact":"8032674188","nameOfClass":"Bollywood for good","genreOfExercise":"Bollywood","noOfSessions":15,"capacity":10,"price":35,"startDateTime":"2021-07-19T20:52:37","endDateTime":"2021-07-19T21:52:37","mode":"Online","location":"Charing Cross","minAge":"18","maxAge":null,"gender":"Male","details":"feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue","typeOfExercise":"Strength","image":"http://dummyimage.com/50x50.png/5fa2dd/ffffff"},
    {"orgName":"Myrwyn Barkworth","email":"mbarkworthl@apple.com","contact":"6059215083","nameOfClass":"Bobsledding only for Bobs","genreOfExercise":"Bobsled","noOfSessions":1,"capacity":20,"price":0,"startDateTime":"2021-08-06T04:49:04","endDateTime":"2021-08-06T05:49:04","mode":"Physical","location":"Ohio","minAge":"21","maxAge":null,"gender":"All","details":"vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu","typeOfExercise":"Strength","image":"http://dummyimage.com/50x50.png/ff4444/ffffff"},
    {"orgName":"Kerstin Vickors","email":"kvickorsm@google.com.hk","contact":"3874957782","nameOfClass":"Kickbox for Hogs","genreOfExercise":"Kickbox","noOfSessions":15,"capacity":30,"price":45,"startDateTime":"2021-10-10T00:38:06","endDateTime":"2021-10-10T01:38:06","mode":"Online","location":"Daystar","minAge":"12","maxAge":null,"gender":"Male","details":"sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet","typeOfExercise":"Endurance","image":"http://dummyimage.com/50x50.png/cc0000/ffffff"},
    {"orgName":"Herve Forgie","email":"hforgien@apache.org","contact":"2213027048","nameOfClass":"Water Polo with Marco","genreOfExercise":"Water Polo","noOfSessions":1,"capacity":30,"price":45,"startDateTime":"2021-08-29T05:25:16","endDateTime":"2021-08-29T06:25:16","mode":"Online","location":"Hollow Ridge","minAge":"7","maxAge":null,"gender":"Male","details":"cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer","typeOfExercise":"Flexibility","image":"http://dummyimage.com/50x50.png/dddddd/000000"},
    {"orgName":"Cherish Yarnold","email":"cyarnoldo@intel.com","contact":"7898803576","nameOfClass":"Abs Buns Thighs","genreOfExercise":"ABT","noOfSessions":12,"capacity":10,"price":0,"startDateTime":"2021-10-17T15:02:54","endDateTime":"2021-10-17T16:02:54","mode":"Online","location":"Mcbride","minAge":"12","maxAge":null,"gender":"All","details":"tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris","typeOfExercise":"Balance","image":"http://dummyimage.com/50x50.png/dddddd/000000"},
    {"orgName":"Lia Cutten","email":"lcuttenp@washington.edu","contact":"4069637993","nameOfClass":"Discus and Biscuits","genreOfExercise":"Discus","noOfSessions":15,"capacity":30,"price":40,"startDateTime":"2021-07-21T15:35:12","endDateTime":"2021-07-21T16:35:12","mode":"Online","location":"Reinke","minAge":"18","maxAge":null,"gender":"Female","details":"nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu","typeOfExercise":"Strength","image":"http://dummyimage.com/50x50.png/ff4444/ffffff"},
    {"orgName":"Roxie Vsanelli","email":"rvsanelliq@printfriendly.com","contact":"5241269136","nameOfClass":"HIIT with Me","genreOfExercise":"HIIT","noOfSessions":10,"capacity":30,"price":20,"startDateTime":"2021-07-30T02:58:51","endDateTime":"2021-07-30T03:58:51","mode":"Online","location":"Del Mar","minAge":"16","maxAge":null,"gender":"Male","details":"ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor","typeOfExercise":"Balance","image":"http://dummyimage.com/50x50.png/cc0000/ffffff"},
    {"orgName":"Di Menary","email":"dmenaryr@naver.com","contact":"8672179539","nameOfClass":"Yoga in the Park","genreOfExercise":"Yoga","noOfSessions":10,"capacity":10,"price":20,"startDateTime":"2021-07-22T12:14:32","endDateTime":"2021-07-22T13:14:32","mode":"Physical","location":"Sachtjen","minAge":"16","maxAge":null,"gender":"Female","details":"at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare","typeOfExercise":"Flexibility","image":"http://dummyimage.com/50x50.png/dddddd/000000"},
    {"orgName":"Nealy Sorton","email":"nsortons@upenn.edu","contact":"6743665041","nameOfClass":"Swimming for kids","genreOfExercise":"Swimming","noOfSessions":10,"capacity":30,"price":25,"startDateTime":"2021-11-05T15:24:54","endDateTime":"2021-11-05T16:24:54","mode":"Physical","location":"Wayridge","minAge":"7","maxAge":null,"gender":"Female","details":"nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla","typeOfExercise":"Endurance","image":"http://dummyimage.com/50x50.png/cc0000/ffffff"},
    {"orgName":"Gherardo Diviny","email":"gdivinyt@amazon.de","contact":"1335721047","nameOfClass":"Swimming for adults","genreOfExercise":"Swimming","noOfSessions":10,"capacity":20,"price":25,"startDateTime":"2021-09-18T06:33:37","endDateTime":"2021-09-18T07:33:37","mode":"Online","location":"Lawn","minAge":"16","maxAge":null,"gender":"Male","details":"libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in","typeOfExercise":"Endurance","image":"http://dummyimage.com/50x50.png/cc0000/ffffff"},
    {"orgName":"Lars Simo","email":"lsimou@privacy.gov.au","contact":"6123764685","nameOfClass":"Basketball for all","genreOfExercise":"Basketball","noOfSessions":15,"capacity":10,"price":0,"startDateTime":"2021-08-22T00:42:50","endDateTime":"2021-08-22T01:42:50","mode":"Physical","location":"Sloan","minAge":"16","maxAge":null,"gender":"All","details":"consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed","typeOfExercise":"Endurance","image":"http://dummyimage.com/50x50.png/dddddd/000000"},
    {"orgName":"Kim Faithorn","email":"kfaithornv@tiny.cc","contact":"8919051305","nameOfClass":"Tennis for mommies","genreOfExercise":"Tennis","noOfSessions":10,"capacity":20,"price":50,"startDateTime":"2021-11-21T16:36:58","endDateTime":"2021-11-21T17:36:58","mode":"Physical","location":"John Wall","minAge":"21","maxAge":null,"gender":"Male","details":"lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt","typeOfExercise":"Balance","image":"http://dummyimage.com/50x50.png/cc0000/ffffff"},
    {"orgName":"Neale Danaher","email":"ndanaherw@nymag.com","contact":"4066237609","nameOfClass":"KpopXFitness finesse","genreOfExercise":"KpopXFitness","noOfSessions":12,"capacity":20,"price":15,"startDateTime":"2021-08-17T08:34:57","endDateTime":"2021-08-17T09:34:57","mode":"Physical","location":"Arkansas","minAge":"16","maxAge":null,"gender":"Female","details":"semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam tristique tortor eu","typeOfExercise":"Strength","image":"http://dummyimage.com/50x50.png/ff4444/ffffff"},
    {"orgName":"Torrance Ferrettini","email":"tferrettinix@geocities.com","contact":"8758311705","nameOfClass":"Bollywood for good","genreOfExercise":"Bollywood","noOfSessions":15,"capacity":30,"price":40,"startDateTime":"2021-11-24T08:59:08","endDateTime":"2021-11-24T09:59:08","mode":"Physical","location":"Stephen","minAge":"null","maxAge":null,"gender":"All","details":"dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas","typeOfExercise":"Strength","image":"http://dummyimage.com/50x50.png/ff4444/ffffff"},
    {"orgName":"Vivyan Moyne","email":"vmoyney@issuu.com","contact":"4687301213","nameOfClass":"Bobsledding only for Bobs","genreOfExercise":"Bobsled","noOfSessions":1,"capacity":20,"price":20,"startDateTime":"2021-09-21T04:20:51","endDateTime":"2021-09-21T05:20:51","mode":"Online","location":"Warbler","minAge":"7","maxAge":null,"gender":"Female","details":"at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam","typeOfExercise":"Balance","image":"http://dummyimage.com/50x50.png/dddddd/000000"},
    {"orgName":"Nancey Bartczak","email":"nbartczakz@so-net.ne.jp","contact":"3894700991","nameOfClass":"Kickbox for Hogs","genreOfExercise":"Kickbox","noOfSessions":1,"capacity":10,"price":20,"startDateTime":"2021-08-05T22:45:28","endDateTime":"2021-08-05T23:45:28","mode":"Online","location":"Derek","minAge":"7","maxAge":null,"gender":"Male","details":"ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus","typeOfExercise":"Balance","image":"http://dummyimage.com/50x50.png/dddddd/000000"},
    {"orgName":"Enrica Mounch","email":"emounch10@bravesites.com","contact":"3671614376","nameOfClass":"Water Polo with Marco","genreOfExercise":"Water Polo","noOfSessions":10,"capacity":30,"price":40,"startDateTime":"2021-10-15T06:58:05","endDateTime":"2021-10-15T07:58:05","mode":"Online","location":"Graceland","minAge":"7","maxAge":null,"gender":"Female","details":"velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat","typeOfExercise":"Balance","image":"http://dummyimage.com/50x50.png/ff4444/ffffff"},
    {"orgName":"Maryjo MacAdie","email":"mmacadie11@unesco.org","contact":"8471422571","nameOfClass":"Abs Buns Thighs","genreOfExercise":"ABT","noOfSessions":15,"capacity":10,"price":20,"startDateTime":"2021-06-30T17:09:19","endDateTime":"2021-06-30T18:09:19","mode":"Physical","location":"Lighthouse Bay","minAge":"null","maxAge":null,"gender":"Male","details":"in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi","typeOfExercise":"Endurance","image":"http://dummyimage.com/50x50.png/dddddd/000000"},
    {"orgName":"Teodora Burrass","email":"tburrass12@youtube.com","contact":"5989560232","nameOfClass":"Discus and Biscuits","genreOfExercise":"Discus","noOfSessions":1,"capacity":20,"price":20,"startDateTime":"2021-10-28T17:23:43","endDateTime":"2021-10-28T18:23:43","mode":"Online","location":"Lighthouse Bay","minAge":"7","maxAge":null,"gender":"All","details":"ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut","typeOfExercise":"Flexibility","image":"http://dummyimage.com/50x50.png/5fa2dd/ffffff"},
    {"orgName":"Jeremie heson","email":"jheson13@businesswire.com","contact":"5671941881","nameOfClass":"HIIT with Me","genreOfExercise":"HIIT","noOfSessions":15,"capacity":20,"price":40,"startDateTime":"2021-09-20T16:03:14","endDateTime":"2021-09-20T17:03:14","mode":"Online","location":"Cardinal","minAge":"18","maxAge":null,"gender":"Female","details":"nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus","typeOfExercise":"Strength","image":"http://dummyimage.com/50x50.png/dddddd/000000"},
    {"orgName":"Luce Ipsgrave","email":"lipsgrave14@wsj.com","contact":"3401544454","nameOfClass":"Yoga in the Park","genreOfExercise":"Yoga","noOfSessions":10,"capacity":10,"price":50,"startDateTime":"2021-08-07T23:09:44","endDateTime":"2021-08-08T00:09:44","mode":"Physical","location":"Waywood","minAge":"18","maxAge":null,"gender":"All","details":"nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut nulla sed accumsan felis ut","typeOfExercise":"Balance","image":"http://dummyimage.com/50x50.png/cc0000/ffffff"},
    {"orgName":"Muriel Bolf","email":"mbolf15@feedburner.com","contact":"6545930526","nameOfClass":"Swimming for kids","genreOfExercise":"Swimming","noOfSessions":15,"capacity":30,"price":25,"startDateTime":"2021-10-07T11:17:41","endDateTime":"2021-10-07T12:17:41","mode":"Online","location":"Jenna","minAge":"12","maxAge":null,"gender":"Male","details":"quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in","typeOfExercise":"Flexibility","image":"http://dummyimage.com/50x50.png/cc0000/ffffff"},
    {"orgName":"Moyna Joder","email":"mjoder16@hexun.com","contact":"1909978068","nameOfClass":"Swimming for adults","genreOfExercise":"Swimming","noOfSessions":10,"capacity":10,"price":50,"startDateTime":"2021-11-19T00:48:45","endDateTime":"2021-11-19T01:48:45","mode":"Online","location":"Ilene","minAge":"null","maxAge":null,"gender":"All","details":"pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque","typeOfExercise":"Strength","image":"http://dummyimage.com/50x50.png/ff4444/ffffff"},
    {"orgName":"Gallard Achrameev","email":"gachrameev17@fotki.com","contact":"3363664092","nameOfClass":"Basketball for all","genreOfExercise":"Basketball","noOfSessions":10,"capacity":30,"price":15,"startDateTime":"2021-09-18T18:03:36","endDateTime":"2021-09-18T19:03:36","mode":"Physical","location":"Utah","minAge":"7","maxAge":null,"gender":"All","details":"ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien","typeOfExercise":"Balance","image":"http://dummyimage.com/50x50.png/cc0000/ffffff"},
    {"orgName":"Katti Easum","email":"keasum18@lulu.com","contact":"1902732854","nameOfClass":"Tennis for mommies","genreOfExercise":"Tennis","noOfSessions":10,"capacity":20,"price":10,"startDateTime":"2021-09-22T17:26:37","endDateTime":"2021-09-22T18:26:37","mode":"Physical","location":"Ohio","minAge":"null","maxAge":null,"gender":"Male","details":"nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus","typeOfExercise":"Flexibility","image":"http://dummyimage.com/50x50.png/ff4444/ffffff"},
    {"orgName":"Enrique Duffit","email":"eduffit19@altervista.org","contact":"3103502128","nameOfClass":"KpopXFitness finesse","genreOfExercise":"KpopXFitness","noOfSessions":10,"capacity":10,"price":25,"startDateTime":"2021-08-19T11:08:04","endDateTime":"2021-08-19T12:08:04","mode":"Online","location":"Barby","minAge":"12","maxAge":null,"gender":"Female","details":"suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien","typeOfExercise":"Flexibility","image":"http://dummyimage.com/50x50.png/cc0000/ffffff"},
    {"orgName":"Olivette Goldsby","email":"ogoldsby1a@etsy.com","contact":"4265558096","nameOfClass":"Bollywood for good","genreOfExercise":"Bollywood","noOfSessions":1,"capacity":20,"price":25,"startDateTime":"2021-10-12T15:07:52","endDateTime":"2021-10-12T16:07:52","mode":"Online","location":"Center","minAge":"18","maxAge":null,"gender":"All","details":"eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas","typeOfExercise":"Endurance","image":"http://dummyimage.com/50x50.png/dddddd/000000"},
    {"orgName":"Susan Euplate","email":"seuplate1b@typepad.com","contact":"8375778593","nameOfClass":"Bobsledding only for Bobs","genreOfExercise":"Bobsled","noOfSessions":15,"capacity":20,"price":0,"startDateTime":"2021-11-19T09:08:02","endDateTime":"2021-11-19T10:08:02","mode":"Physical","location":"Mendota","minAge":"null","maxAge":null,"gender":"All","details":"vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel","typeOfExercise":"Strength","image":"http://dummyimage.com/50x50.png/ff4444/ffffff"},
    {"orgName":"Jeri Melmar","email":"jmelmar1c@sina.com.cn","contact":"7704101481","nameOfClass":"Kickbox for Hogs","genreOfExercise":"Kickbox","noOfSessions":15,"capacity":20,"price":10,"startDateTime":"2021-11-02T01:54:32","endDateTime":"2021-11-02T02:54:32","mode":"Online","location":"Homewood","minAge":"null","maxAge":null,"gender":"Male","details":"in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum","typeOfExercise":"Balance","image":"http://dummyimage.com/50x50.png/5fa2dd/ffffff"},
    {"orgName":"Davon Caveill","email":"dcaveill1d@bloglines.com","contact":"2278076952","nameOfClass":"Water Polo with Marco","genreOfExercise":"Water Polo","noOfSessions":10,"capacity":20,"price":10,"startDateTime":"2021-07-10T08:42:14","endDateTime":"2021-07-10T09:42:14","mode":"Online","location":"Service","minAge":"16","maxAge":null,"gender":"All","details":"aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus","typeOfExercise":"Endurance","image":"http://dummyimage.com/50x50.png/5fa2dd/ffffff"}
]


//create slugs from nameOfClass

data = data.map(item => {
    item.slug = _.kebabCase(item.nameOfClass)
    item.startDay = moment(item.startDateTime).format('ddd')
    item.endDay = moment(item.endDateTime).format('ddd')
    
    return item
})

let connection = null;

//connect to mongodb via mongoose
mongoose.connect(mongoURI, { useNewUrlParser: true, useUnifiedTopology: true } )
    .then(connResp => {
        connection = connResp
        return ClassModel.insertMany(data)
    })
    .then(insertResp => {
        console.log('successful data insertion')
    })
    .catch(err => {
        console.log(err)
    })
    .finally(() => {
        if (connection !== null) {
            connection.disconnect()
        }
    })